#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as bash or
#       ksh, you may want to run it with that shell instead.
#
#   (2) The Java virtual machine's support for option -X is not standard and
#       may not be supported by all JVMs. It is necessary to contact the actual
#       Java vendor in order to verify the use of such an option.
#
##############################################################################

if [ -z "$JAVA_HOME" ] ; then
    JAVA_EXE="`which java`"
    if [ -z "$JAVA_EXE" ] ; then
        echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
        echo ""
        echo "Please set the JAVA_HOME variable in your environment to match the"
        echo "location of your Java installation."
        exit 1
    fi
    JAVA_DIR="`dirname \"$JAVA_EXE\"`"
    JAVA_HOME="`cd \"$JAVA_DIR\" && pwd`"
    export JAVA_HOME
else
    JAVA_EXE="$JAVA_HOME/bin/java"
    if [ ! -x "$JAVA_EXE" ] ; then
        echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
        echo ""
        echo "Please set the JAVA_HOME variable in your environment to match the"
        echo "location of your Java installation."
        exit 1
    fi
fi

if [ -z "$JAVACMD" ] ; then
    if [ -n "$JAVA_HOME"  ] ; then
        if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
            JAVACMD="`$JAVA_HOME/jre/sh/java`"
        else
            JAVACMD="`$JAVA_HOME/bin/java`"
        fi
    else
        JAVACMD="`which java`"
    fi
fi

if [ ! -x "$JAVACMD" ] ; then
    echo "ERROR: JAVA_HOME is not defined correctly." >&2
    echo "  We cannot execute $JAVACMD" >&2
    exit 1
fi

if [ -z "$JAVA_HOME" ] ; then
    echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2
    echo ""
    echo "Please set the JAVA_HOME variable in your environment to match the" >&2
    echo "location of your Java installation." >&2
    exit 1
fi

# Increase the maximum file descriptors if we can.
if [ -n "$MAX_FD" ] ; then
    MAX_FD_LIMIT=`ulimit -H -n`
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# For Darwin, add options to specify how the application appears in the dock
if $darwin; then
    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin or MSYS, switch paths to Windows-style short names.
if [ "$cygwin" = "true" -o "$msys" = "true" ] ; then
    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
    CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`

    JAVACMD=`cygpath --unix "$JAVACMD"`

    # We build the pattern for arguments to be converted via cygpath
    ROOTDIRSRAW=`find -L / -maxdepth 3 -type d -name java >/dev/null 2>&1 && echo "yes" || echo "no"`
    if [ "$ROOTDIRSRAW" = "yes" ] ; then
        ROOTDIRS=`find -L / -maxdepth 3 -type d -name java 2>/dev/null | head -9 "`
    fi
    SEP=""
    for dir in $ROOTDIRS ; do
        ROOTDIR="$dir"
        case "$ROOTDIR" in
            *"$SEP"*)
                SEP="|"
                ;;
        esac
    done
    OURCYGPATTERN="(^($ROOTDIR))"
    APP_CYGPATTERN="$OURCYGPATTERN"
    rel_app_home=`$ECHO "$APP_HOME" | $SED 's%^%/%'`
    APP_HOME=`$ECHO "$APP_HOME$rel_app_home" | $SED 's%//%/%g'`
    CLASSPATH=`$ECHO "$CLASSPATH" | $SED 's%:% %g'`

    JAVACMD=`$ECHO "$JAVACMD" | $SED 's%^\(.*\)$%\1%g'`
    JAVACMD=`cygpath --unix "$JAVACMD"`
fi

exec "$JAVACMD" "$@"
